package operators;
import utils.Tuple;

/**
 * Abstract class for Operator. Consists of common methods
 * to be implemented by all operators.
 * @author Gaurav, Tanvi and Sahana (gk368,tmm259 and sv387)
 */
public abstract class Operator {

	/**
	 * Gets the next tuple from the table
	 * @return next tuple that satifies operator's conditions
	 */
	public abstract Tuple getNextTuple();
    
	/**
	 * Resets the getNextTuple to start from the beginning of the table
	 */
	public abstract void reset();
	
	public void reset(int index) {
		
	}
	
	/**
	 * Prints the output generated by the operator
	 */
    public void dump() {
		Tuple currentTuple = getNextTuple();
		String tableDump = null;
		if (currentTuple != null)
			tableDump = new String(currentTuple.toStringAttributes()+"\n");
		while(currentTuple != null) {
			tableDump = tableDump + currentTuple.toStringValues() +  "\n";
			currentTuple = getNextTuple();
		}
		System.out.println(tableDump);
    }
}
