package operators;
import java.io.FileNotFoundException;

import utils.Tuple;

/**
 * Abstract class for Operator. Consists of common methods
 * to be implemented by all operators.
 * @author Gaurav, Tanvi and Sahana (gk368,tmm259 and sv387)
 */
public abstract class Operator {

	int count = 0;
	/**
	 * Gets the next tuple from the table
	 * @return next tuple that satifies operator's conditions
	 */
	public abstract Tuple getNextTuple();
    
	/**
	 * Resets the getNextTuple to start from the beginning of the table
	 */
	public abstract void reset();
	
	public void reset(int index) {
		
	}
	
	/**
	 * Prints the output generated by the operator
	 * @throws FileNotFoundException 
	 */
    public void dump() {
		Tuple currentTuple = getNextTuple();
		String tableDump = null;
		if (currentTuple != null){
			tableDump = new String(count++ + " " + currentTuple.toStringAttributes()+"\n");
		}
			
		while(currentTuple != null) {
			tableDump = tableDump + count++ + " " + currentTuple.toStringValues() +  "\n";
			currentTuple = getNextTuple();
		}
		System.out.println(tableDump);
//		PrintWriter out = null;
//		try {
//			out = new PrintWriter("hello.txt");
//		} catch (FileNotFoundException e) {
//			e.printStackTrace();
//		}
//		out.write(tableDump);
//		out.close();
    }
}
